pipeline {
    agent {
	kubernetes {
	    label "jenkins-golang-skopeo-agent"
	    cloud "openshift"
            inheritFrom "maven"
	    containerTemplate {
		name "jnlp"
		image "image-registry.openshift-image-registry.svc:5000/golang-jenkins-demo/jenkins-agent-appdev"
		resourceRequestMemory "2Gi"
		resourceLimitMemory "2Gi"
		resourceRequestCpu "2"
		resourceLimitCpu "2"
	    }
	}
    }


    stages {
        stage('Checkout Source') {
            steps {
                checkout scm      
            }
        }
        stage('Unit Test'){
            steps {
                dir('go_app_1'){
                    script {
                        sh "go test"
                    }
                }
            }
        }
        stage('Build'){
            steps {
                dir('go_app_1/cmd'){
                    script {
                        sh "go build"
                    }
                }
            }
        }
        stage('Upload Binary'){
            steps {
                dir('go_app_1/cmd'){
                    script {
                        sh "curl -v -u admin:pass#123 --upload-file cmd http://nexus.golang-jenkins-demo.svc.cluster.local:8081/repository/binaries/go_app_1/$BUILD_NUMBER/go_app_1"
                    }
                }
            }
        }
        stage('Build Container'){
            steps {
                script{
                    openshift.withCluster(){
                        openshift.withProject("") {
                            def buildconfig = openshift.selector("bc","go-app-1")
                            buildconfig.source.dockerfile.value = """FROM scratch
ADD http://nexus.golang-jenkins-demo.svc.cluster.local:8081/repository/binaries/go_app_1/$BUILD_NUMBER/go_app_1 /go_app_1
USER appuser:appuser
ENTRYPOINT [ "/go_app_1" ]
"""                        buildconfig.startBuild("--wait=true")                        
                        }
                    }
                }
            }
        }
    }
}
