pipeline {
    agent {
	kubernetes {
	    label "jenkins-golang-skopeo-agent"
	    cloud "openshift"
            inheritFrom "maven"
	    containerTemplate {
		name "jnlp"
		image "image-registry.openshift-image-registry.svc:5000/golang-jenkins-demo/jenkins-agent-appdev"
		resourceRequestMemory "2Gi"
		resourceLimitMemory "2Gi"
		resourceRequestCpu "2"
		resourceLimitCpu "2"
	    }
	}
    }


    stages {
        stage('Checkout Source') {
            steps {
                checkout scm      
            }
        }
        stage('Unit Test'){
            steps {
                dir('go_app_1'){
                    script {
                        sh "go test"
                    }
                }
            }
        }
        stage('Build'){
            steps {
                dir('go_app_1/cmd'){
                    script {
                        sh "go build"
                    }
                }
            }
        }
    }
}
